### ISSUE TITLE
Send email to several recipients, with CC and CCO

### ISSUE THREAD

**Issue by juangarias** [openedx/edx-ace#106]
* edx version: **ironwood**
* edx-ace version: **edx-ace==0.1.10**
* Django version: **django==1.11.23**
* Python version: **2.7**
* Operating System: **Ubuntu 18.04.5**

### Description

I want to send an email to several recipients and in CC and CCO.

**Comment by nedbat** [comment]
Please see https://openedx.org/getting-help for the Slack and Discourse links.
