### ISSUE TITLE
Master build fails on travis for python 3.5

### ISSUE THREAD

**Issue by BenjiLee** [openedx/edx-ace#32]
master build is failing on travis. There seems to be an issue with uploading an already existing file on pypi. https://pypi.org/help/#file-name-reuse

For python 2, it looks like that step is skipped as mentioned in the travis log output. 
```
Skipping a deployment with the pypi provider because this is not on the required runtime
```

**Comment by OmarIthawi** [comment]
Thanks @BenjiLee. The issue has been fixed and now master is succeeding on Travis. I'm closing this PR.

cc: @natabene
